language: python
python:
- 2.7
cache: pip
  - pip install codecov
  - pip install coverage

script: 
  - python test.py # command to run unit test
  - coverage run test.py # command to run code coverage
#can do additional things, say send out reports, which we will discuss next time
after_success:
 - codecov
